name: Auto Date Tracking for All Issues

on:
  workflow_dispatch:

permissions:
  issues: write
  contents: read

jobs:
  auto-date-tracking:
    runs-on: ubuntu-latest
    steps:
      - name: Set Start and Completion Dates on All Issues
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const owner = context.repo.owner;
            const repo = context.repo.repo;

            const now = new Date().toISOString().split("T")[0];

            const issues = await github.paginate(
              github.rest.issues.listForRepo,
              {
                owner,
                repo,
                state: "all",
                per_page: 100
              }
            );

            for (const issue of issues) {
              // Skip pull requests
              if (issue.pull_request) continue;

              const issue_number = issue.number;
              const labels = issue.labels.map(label => label.name);

              const comments = await github.rest.issues.listComments({
                owner,
                repo,
                issue_number
              });

              const alreadyHas = (text) =>
                comments.data.some(c => c.body.includes(text));

              if (labels.includes("In Progress") && !alreadyHas("🕒 Start Date:")) {
                await github.rest.issues.createComment({
                  owner,
                  repo,
                  issue_number,
                  body: `🕒 **Start Date:** ${now}`
                });
                console.log(`✅ Start Date set on issue #${issue_number}`);
              }

              if (
                issue.state === "closed" && !alreadyHas("✅ Completion Date:")
              ) {
                await github.rest.issues.createComment({
                  owner,
                  repo,
                  issue_number,
                  body: `✅ **Completion Date:** ${now}`
                });
                console.log(`✅ Completion Date set on issue #${issue_number}`);
              }
            }

            console.log("🎉 Finished processing all issues.");
