name: Auto Date Tracking

on:
  workflow_dispatch:
  issues:
    types: [edited, closed]

jobs:
  auto-date-tracking:
    runs-on: ubuntu-latest
    steps:
      - name: Set Start and Completion Dates
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const issue = context.payload.issue;


            const issue_number = context.issue.number;
            const owner = context.repo.owner;
            const repo = context.repo.repo;

            const labels = issue.labels.map(label => label.name) || [];
            const now = new Date().toISOString().split("T")[0];

            const comments = await github.rest.issues.listComments({
              owner,
              repo,
              issue_number
            });

            const alreadyHas = (text) => comments.data.some(c => c.body.includes(text));

            if (labels.includes("In Progress") && !alreadyHas("🕒 Start Date:")) {
              await github.rest.issues.createComment({
                owner,
                repo,
                issue_number,
                body: `🕒 **Start Date:** ${now}`
              });
              console.log("✅ Start Date set");
            }

            if (issue.state === "closed" && labels.includes("Complete") && !alreadyHas("✅ Completion Date:")) {
              await github.rest.issues.createComment({
                owner,
                repo,
                issue_number,
                body: `✅ **Completion Date:** ${now}`
              });
              console.log("✅ Completion Date set");
            }
